//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositorioMagic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MTGEntities : DbContext
    {
        public MTGEntities()
            : base("name=MTGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CARD> CARD { get; set; }
        public virtual DbSet<EXPANSION> EXPANSION { get; set; }
        public virtual DbSet<SUBTIPO> SUBTIPO { get; set; }
        public virtual DbSet<TIPO> TIPO { get; set; }
    }
}
